# The file will contain all tag poses in the environment: [x, y, z, Roll, Pitch, Yaw] (measured in meters and radians).

tag_poses:
  0: [-2.5, -2.489, 0.3, 1.5708, 0.0, 3.14159]
  1: [-1.5, -2.489, 0.3, 1.5708, 0.0, 3.14159]




